[package]
name = "mycelium-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
autobins = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1"
libloading = "0.8"
mycelium-display = { path = "display" }
mycelium-input = { path = "input" }
mycelium-board = { path = "board" }
mycelium-gps = { path = "gps" }
mycelium-storage = { path = "storage" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
